# Generated by Django 4.0.6 on 2022-07-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='标题'),
        ),
    ]
