# Generated by Django 4.0.6 on 2022-07-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsserver', '0002_alter_department_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='user',
        ),
    ]
