# Generated by Django 4.0.6 on 2022-07-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipsserver', '0003_alter_department_table_alter_userinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsserver.department', verbose_name='部门'),
        ),
    ]
